// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAig5ugBXvyKdqM_FK0YFEWqhzCKBWgoEU',
    appId: '1:620710507545:web:74169717983444124ca688',
    messagingSenderId: '620710507545',
    projectId: 'apimovil-2b24a',
    authDomain: 'apimovil-2b24a.firebaseapp.com',
    storageBucket: 'apimovil-2b24a.appspot.com',
    measurementId: 'G-11VHYN462R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-k5CH41zfcf4FibdDHs3oAGWa7Nt0rjs',
    appId: '1:620710507545:android:be631dd1c72f6ca04ca688',
    messagingSenderId: '620710507545',
    projectId: 'apimovil-2b24a',
    storageBucket: 'apimovil-2b24a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHrR1YxTchgrNu4Pf7OLR7sl_lfjdBlQ',
    appId: '1:620710507545:ios:35b7a557d40ad68e4ca688',
    messagingSenderId: '620710507545',
    projectId: 'apimovil-2b24a',
    storageBucket: 'apimovil-2b24a.appspot.com',
    iosClientId: '620710507545-6a3iu6b9nqmj39o5ctj41ocj2bse2l7b.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHrR1YxTchgrNu4Pf7OLR7sl_lfjdBlQ',
    appId: '1:620710507545:ios:35b7a557d40ad68e4ca688',
    messagingSenderId: '620710507545',
    projectId: 'apimovil-2b24a',
    storageBucket: 'apimovil-2b24a.appspot.com',
    iosClientId: '620710507545-6a3iu6b9nqmj39o5ctj41ocj2bse2l7b.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );
}
